apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-chatbot
  labels:
    app: capstone-chatbot
  namespace: default
spec:
  selector:
    matchLabels:
      app: capstone-chatbot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-chatbot
    spec:
      containers:
      - image: bolobolobobjenkins/capstone-chatbot:latest
        imagePullPolicy: Always
        name: capstone-chatbot
        ports:
        - containerPort: 5000
          protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: capstone-chatbot
spec:
  type: LoadBalancer
  selector:
    app: capstone-chatbot
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 500

---

kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: capstone-chatbot
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: capstone-chatbot
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 80