Description: >
    Charles Gery / Udacity
    Deploy a High-Availability Web App using CloudFormation
    This template deploys a bastion in a public subnet

Parameters:

    EnvName:
        Description: Environment Name
        Type: String
        Default: UdacityProject

    VPCCIDR:
        Description: IP Range of the VPC
        Type: String
        Default: 10.0.0.0/16
    
Resources:
    
    BastionSecGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
          GroupDescription: SSH from my IP
          VpcId:
              Fn::ImportValue:
                !Sub "${EnvName}-VPCID"
          SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
    
    BastionInstance:
        Type: AWS::EC2::Instance
        Properties:
            InstanceType: t2.micro
            KeyName: bastion-udacity-project2
            NetworkInterfaces:
              - AssociatePublicIpAddress: true
                DeviceIndex: 0
                GroupSet:
                  - Ref: BastionSecGroup
                SubnetId:
                  Fn::ImportValue:
                    !Sub "${EnvName}-PUB1-SN"
            ImageId: ami-0d1cd67c26f5fca19
  
    