Description: >
  Charles Gery / Udacity
  Deploy a High-Availability Web App using CloudFormation
  This template deploys the eks cluster of the project

Parameters:
  EnvName:
    Description: Name of the environment
    Type: String
    Default: UdacityProject

Resources:

  EKSCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: !Sub "${EnvName}-CLUSTER"
      ResourcesVpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub "${EnvName}-CPSG"
        SubnetIds:
          - Fn::ImportValue: !Sub "${EnvName}-PUB1-SN"
          - Fn::ImportValue: !Sub "${EnvName}-PUB2-SN"
          - Fn::ImportValue: !Sub "${EnvName}-PRI1-SN"
          - Fn::ImportValue: !Sub "${EnvName}-PRI2-SN"
      RoleArn: arn:aws:iam::244468422315:role/eksRole

Outputs:

  EKSCluster:
    Description: The EKS Cluster
    Value: !Ref EKSCluster
    Export:
      Name: !Sub "${EnvName}-CLUSTER"
