Description: >
    Charles Gery / Udacity
    Deploy a High-Availability Web App using CloudFormation
    This template deploys a Jenkins server in a public subnet

Parameters:

    EnvName:
        Description: Environment Name
        Type: String
        Default: CapstoneProject

    VPCCIDR:
        Description: IP Range of the VPC
        Type: String
        Default: 10.0.0.0/16
    
Resources:
    
    JenkinsSecGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
          GroupDescription: SSH from my IP
          VpcId:
              Fn::ImportValue:
                !Sub "${EnvName}-VPCID"
          SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 8080
            ToPort: 8080
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0
    
    
    BastionInstance:
        Type: AWS::EC2::Instance
        Properties:
            InstanceType: m5.large
            KeyName: jenkins-key
            NetworkInterfaces:
              - AssociatePublicIpAddress: true
                DeviceIndex: 0
                GroupSet:
                  - Ref: JenkinsSecGroup
                SubnetId:
                  Fn::ImportValue:
                    !Sub "${EnvName}-PUB1-SN"
            ImageId: ami-0d1cd67c26f5fca19
            BlockDeviceMappings:
                - DeviceName: "/dev/xvda"
                  Ebs:
                    VolumeSize: '20'
            UserData:
                Fn::Base64: !Sub |
                    #!/bin/bash
                    apt-get update -y
                    apt install -y default-jdk
                    wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
                    sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
                    sudo apt-get update
                    sudo apt-get install -y jenkins
                    sudo systemctl start jenkins
                    sudo systemctl enable jenkins
                    sudo systemctl status jenkins
                    apt install tidy -y
                    sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.17.5/hadolint-Linux-x86_64
                    sudo chmod +x /bin/hadolint
                    sudo apt install docker.io -y
                    sudo apt-get update && sudo apt-get install -y apt-transport-https
                    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
                    echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
                    sudo apt-get update
                    sudo apt-get install -y kubectl

