Description: >
    Charles Gery / Udacity
    Deploy a High-Availability Web App using CloudFormation
    This template deploys the servers part of the project (LoadBalancer, EC2 instances...)

Parameters:

    EnvName:
        Description: Environment Name
        Type: String
        Default: UdacityProject

    VPCCIDR:
        Description: IP Range of the VPC
        Type: String
        Default: 10.0.0.0/16
    
    LBIngressCIDR:
        Description: IP range of the SecurityGroupIngress of the LB
        Type: String
        Default: 0.0.0.0/0

    LBEgressCIDR:
        Description: IP range of the SecurityGroupEgress of the LB
        Type: String
        Default: 0.0.0.0/0
    
    WSIngressCIDR:
        Description: IP range of the SecurityGroupIngress of the web servers
        Type: String
        Default: 0.0.0.0/0

    WSEgressCIDR:
        Description: IP range of the SecurityGroupEgress of the web servers
        Type: String
        Default: 0.0.0.0/0

    LCInstanceType:
        Description: LaunchConfigInstanceType
        Type: String
        Default: t3.medium
    
    LCImageId:
        Description: Launch config image id
        Type: String
        Default: ami-0d1cd67c26f5fca19
    
    LCKeyName:
        Description: Launch config key name
        Type: String
        Default: webservers-udacity-project2
    
Resources:

    LBSecGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow HTTP to LB
            VpcId:
                Fn::ImportValue:
                    !Sub "${EnvName}-VPCID"
            SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: !Ref LBIngressCIDR
            SecurityGroupEgress:
            - IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: !Ref LBEgressCIDR
    
    WebServersSecGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: HTTP to host, SSH from local (for connection from bastion)
            VpcId:
                Fn::ImportValue:
                    !Sub "${EnvName}-VPCID"
            SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: !Ref WSIngressCIDR
            - IpProtocol: tcp
              FromPort: 22
              ToPort: 22
              CidrIp: !Ref VPCCIDR
            SecurityGroupEgress:
            - IpProtocol: tcp
              FromPort: 0
              ToPort: 65535
              CidrIp: !Ref WSEgressCIDR
    
    IAMRoleS3Reader:
        Type: AWS::IAM::InstanceProfile
        Properties:
            Roles:
                - S3Reader
    
    LaunchConfig:
        Type: AWS::AutoScaling::LaunchConfiguration
        Properties:
            AssociatePublicIpAddress: false
            IamInstanceProfile: !Ref IAMRoleS3Reader
            UserData:
                Fn::Base64: !Sub |
                    #!/bin/bash
                    apt-get update -y
                    apt-get install unzip awscli -y
                    apt-get install apache2 -y
                    systemctl start apache2.service
                    cd /var/www/html
                    aws s3 cp s3://udacity-devops-project2/index.zip .
                    unzip -o index.zip
            ImageId: !Ref LCImageId
            KeyName: !Ref LCKeyName
            SecurityGroups:
            - Ref: WebServersSecGroup
            InstanceType: !Ref LCInstanceType
            BlockDeviceMappings:
            - DeviceName: "/dev/sdk"
              Ebs:
                VolumeSize: '10'
    
    WebAppASGroup:
        Type: AWS::AutoScaling::AutoScalingGroup
        Properties:
            VPCZoneIdentifier:
            - Fn::ImportValue: 
                !Sub "${EnvName}-PRIV-NETS"
            LaunchConfigurationName:
                Ref: LaunchConfig
            MinSize: '4'
            MaxSize: '4'
            TargetGroupARNs:
            - Ref: WebAppTargetGroup
            HealthCheckGracePeriod: 60
    
    LoadBalancer:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            Subnets:
            - Fn::ImportValue: !Sub "${EnvName}-PUB1-SN"
            - Fn::ImportValue: !Sub "${EnvName}-PUB2-SN"
            SecurityGroups:
            - Ref: LBSecGroup
    
    Listener:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
            DefaultActions:
            - Type: forward
              TargetGroupArn:
                Ref: WebAppTargetGroup
            LoadBalancerArn:
                Ref: LoadBalancer
            Port: '80'
            Protocol: HTTP
    
    ListenerRule:
        Type: AWS::ElasticLoadBalancingV2::ListenerRule
        Properties:
            Actions:
            - Type: forward
              TargetGroupArn: !Ref 'WebAppTargetGroup'
            Conditions:
            - Field: path-pattern
              Values: [/]
            ListenerArn: !Ref 'Listener'
            Priority: 1
    
    WebAppTargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            HealthCheckEnabled: true
            HealthCheckIntervalSeconds: 30
            HealthCheckPath: /
            HealthCheckProtocol: HTTP
            HealthCheckTimeoutSeconds: 8
            HealthyThresholdCount: 2
            Port: 80
            Protocol: HTTP
            UnhealthyThresholdCount: 5
            VpcId: 
                Fn::ImportValue:
                    Fn::Sub: "${EnvName}-VPCID"

Outputs:

    DNSName:
        Description: The DNS name of the load balancer
        Value: !Sub http://${LoadBalancer.DNSName}
        Export:
            Name: !Sub ${EnvName}-DNSNAME

    

